In [5]:
import torch
x = torch.tensor([1,2,3,4])
y = torch.tensor([1,2,3,4])
y*x


tensor([ 1,  4,  9, 16])

In [2]:
torch.cat((x,y),dim=0)

tensor([1, 2, 3, 4, 1, 2, 3, 4])

In [3]:
x == y

tensor([True, True, True, True])

In [6]:
x = x.reshape(4,1)
z = x+y

In [8]:

z[1,1] = 0
z

tensor([[2, 3, 4, 5],
        [3, 0, 5, 6],
        [4, 5, 6, 7],
        [5, 6, 7, 8]])

In [12]:
z[:,1:2] = 0
z

tensor([[2, 0, 4, 5],
        [3, 0, 5, 6],
        [4, 0, 6, 7],
        [5, 0, 7, 8]])

In [13]:
x[3]

tensor([4])

In [14]:
len(x)

4

In [17]:

x

tensor([[1],
        [2],
        [3],
        [4]])

In [19]:
x = torch.tensor([1,2,3,4], dtype=torch.float32)
x.requires_grad_(True)
x.grad

In [20]:
y = 2*torch.dot(x,x)
y

tensor(60., grad_fn=<MulBackward0>)

In [23]:
y.backward()
x.grad 

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.